---
- name: Change default port number in /etc/default/jenkins
  ansible.builtin.lineinfile:
    path: /etc/default/jenkins
    regexp: '^HTTP_PORT='
    line: HTTP_PORT=9000
  become: yes

- name: Create Directory For Jenkins(Groovy Script)
  file:
    path: "/var/lib/jenkins/init.groovy.d"
    state: directory
    mode: 0755
  register: groovy_dir
  become: yes

- name: Copy Groovy script for admin (default user) creation
  template:
    force: yes
    src: "/bakerx/cm/roles/config-jenkins/templates/jenkins-user.groovy.j2"
    dest: "/var/lib/jenkins/init.groovy.d/basic-security.groovy"
    mode: 0755
  become: yes

- name: Copy .vault-pass from current directory to the VM home directory
  copy:
    src: /bakerx/.vault-pass
    dest: "~/"
    mode: 0400

- name: Ensure Jenkins service is restarted
  service:
    name: jenkins
    state: restarted
  become: yes

- name: Install build-pipeline-plugin
  jenkins_plugin:
    name: build-pipeline-plugin
    state: latest
    url: http://localhost:9000
    url_username: admin
    url_password: admin
    timeout: 30
  register: install
  until: install is not failed
  retries: 10
  delay: 2

- name: Ensure Jenkins service is restarted after installing plugins
  service:
    name: jenkins
    state: restarted
  become: yes
