---
- name: Change default port number in /etc/default/jenkins
  ansible.builtin.lineinfile:
    path: /etc/default/jenkins
    regexp: '^HTTP_PORT='
    line: HTTP_PORT=9000
  become: yes

- name: Create Directory For Jenkins(Groovy Script)
  file:
    path: "/var/lib/jenkins/init.groovy.d"
    state: directory
    # mode: 0777
  register: groovy_dir
  become: yes

- name: Copy Groovy script for admin (default user) creation
  template:
    force: yes
    src: "/bakerx/cm/roles/config-jenkins/templates/basic-security.groovy"
    dest: "/var/lib/jenkins/init.groovy.d/basic-security.groovy"
    # mode: 0777
  become: yes

- name: Ensure Jenkins service is restarted
  service:
    name: jenkins
    state: restarted
    enabled: yes
  become: yes

- name: Wait for jenkins to start up
  wait_for:
    timeout: 180
  delegate_to: localhost

- name: Install build-pipeline-plugin in Jenkins server
  jenkins_plugin:
    name: build-pipeline-plugin
    state: latest
    url: http://localhost:9000
    url_username: admin
    url_password: admin
  register: install
  until: install is not failed
  retries: 10
  delay: 5

- name: Ensure Jenkins service is restarted after installing plugins
  service:
    name: jenkins
    state: restarted
  become: yes
