---
- name: Change default port number in /etc/default/jenkins
  ansible.builtin.lineinfile:
    path: /etc/default/jenkins
    regexp: '^HTTP_PORT='
    line: HTTP_PORT={{ JENKINS_PORT }}
  become: yes

- name: Create Directory For Jenkins(Groovy Script)
  file:
    path: "/var/lib/jenkins/init.groovy.d"
    state: directory
  register: groovy_dir
  become: yes

- name: Copy Groovy script for admin (default user) creation
  template:
    force: yes
    src: "/bakerx/cm/roles/config-jenkins/templates/basic-security.groovy"
    dest: "/var/lib/jenkins/init.groovy.d/basic-security.groovy"
  become: yes

- name: Ensure Jenkins service is restarted
  service:
    name: jenkins
    state: restarted
    enabled: yes
  become: yes

- name: Wait for jenkins to start up
  wait_for:
    timeout: 180
  delegate_to: localhost

- name: Install jenkins-job-builder
  jenkins_plugin:
    name: jenkins-job-builder
    state: latest
    url: "{{ JENKINS_URL }}"
    url_username: "{{ JENKINS_USERNAME }}"
    url_password: "{{ JENKINS_PASSWORD }}"
  register: install1
  until: install1 is not failed
  retries: 10
  delay: 5
  become: yes

- name: Install workflow-aggregator
  jenkins_plugin:
    name: workflow-aggregator
    state: latest
    url: "{{ JENKINS_URL }}"
    url_username: "{{ JENKINS_USERNAME }}"
    url_password: "{{ JENKINS_PASSWORD }}"
  register: install2
  until: install2 is not failed
  retries: 10
  delay: 5
  become: yes

- name: Install ws-cleanup
  jenkins_plugin:
    name: ws-cleanup
    state: latest
    url: "{{ JENKINS_URL }}"
    url_username: "{{ JENKINS_USERNAME }}"
    url_password: "{{ JENKINS_PASSWORD }}"
  register: install3
  until: install3 is not failed
  retries: 10
  delay: 5
  become: yes

- name: Install github
  jenkins_plugin:
    name: github
    state: latest
    url: "{{ JENKINS_URL }}"
    url_username: "{{ JENKINS_USERNAME }}"
    url_password: "{{ JENKINS_PASSWORD }}"
  register: install4
  until: install4 is not failed
  retries: 10
  delay: 5
  become: yes

- name: Ensure Jenkins service is restarted after installing plugins
  service:
    name: jenkins
    state: restarted
  become: yes
