---

- name: Create server folder in VM home target
  file:
    path: /home/vagrant/server/
    state: directory
    mode: '0755'

- name: Copy proxy.js to server on monitor VM
  template:
    src: proxy.js
    dest: /home/vagrant/server/proxy.js
    force: yes

- name: Copy package.json to server on monitor VM
  template:
    src: package.json
    dest: /home/vagrant/server/package.json
    force: yes

- name: Copy survey.json to server on monitor VM
  template:
    src: survey.json
    dest: /home/vagrant/server/survey.json
    force: yes

- name: Install npm packages
  npm:
    path: /home/vagrant/server/
