---

- name: Stop agent health service using pm2
  shell: pm2 stop agentHealth
  ignore_errors: yes
  when: inventory_hostname != "proxy"

- name: Start agent health service using pm2 (blue)
  shell: 
    cmd: pm2 start index.js --name agentHealth -- blue
    chdir: /home/vagrant/agent/
  when: inventory_hostname == "blue"

- name: Start agent health service using pm2 (green)
  shell: 
    cmd: pm2 start index.js --name agentHealth -- green
    chdir: /home/vagrant/agent/
  when: inventory_hostname == "green"

- name: Stop server health service using pm2
  shell: pm2 stop proxyServer
  ignore_errors: yes
  when: inventory_hostname == "proxy"

- name: Start server health service using pm2
  shell: 
    cmd: pm2 start proxy.js --name proxyServer
    chdir: /home/vagrant/server/
  when: inventory_hostname == "proxy"
