---
- name: Copy .vault-pass from current directory to the VM home directory
  copy:
    src: /bakerx/.vault-pass
    dest: "~/"
    mode: 0400

- name: Add environment variables for node app and mongodb to bashrc
  lineinfile:
    path: "/etc/environment"
    line: "{{item}}"
  loop: "{{ lookup('file', '../.env_vars.txt').splitlines() }}"
  become: yes

- name: install mongodb
  apt:
    name: mongodb
    state: latest
    update_cache: yes
  become: true

- name: install pip
  apt:
    name: python3-pip
    state: latest
    update_cache: yes
  become: true

- name: "Install pymongo"
  pip:
    name: pymongo
    state: latest
  become: true

- name: Create mongo user with password and readWrite role
  mongodb_user:
    database: "{{ lookup('env', 'MONGO_DB') }}"
    name: "{{ lookup('env', 'MONGO_USER') }}"
    password: "{{ lookup('env', 'MONGO_PASSWORD') }}"
    roles: readWrite
    state: present
  become: true

- name: "Add nodejs apt key"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  become: true

- name: "Add nodejs 14.x ppa for apt repo"
  apt_repository:
    repo: deb https://deb.nodesource.com/node_14.x focal main
    update_cache: yes
    state: present
  become: true

- name: "Install nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: latest
    install_recommends: yes
  become: true
