---

# - name: Import the public key used by the package management system
#   apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10 state=present

# - name: Add MongoDB repository
#   apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present


- name: install mongodb
  apt:
    name: mongodb
    state: latest
    update_cache: yes
  become: true

- name: install pip
  apt:
    name: python3-pip
    state: latest
    update_cache: yes
  become: true


- name: "Install pymongo"
  pip:
    name: pymongo
    state: latest

- name: Create mongo user with password and readWrite role
  mongodb_user:
    database: "{{DATABASE_NAME}}"
    name: "{{MONGO_USER}}"
    password: "{{MONGO_PASSWORD}}"
    roles: "admin"
    state: present
  become: true

- name: "Add nodejs apt key"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  become: yes

- name: "Add nodejs 14.x ppa for apt repo"
  apt_repository:
    repo: deb https://deb.nodesource.com/node_14.x bionic main
    # repo: "deb https://deb.nodesource.com/node_8.x xenial main"
    update_cache: yes
    state: present
  become: yes

- name: "Install nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: present
  become: yes
