---
- name: Install OpenJDK 8 using apt
  apt:
    name: openjdk-8-jdk
    state: latest
    install_recommends: no
  become: true

- name: Install jenkins apt repository key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present
  become: yes

- name: Add jenkins repo is added to apt source
  apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present
  become: yes

- name: Install jenkins via apt
  apt:
    name: jenkins
    update_cache: yes
  become: yes

- name: Change default port number in /etc/default/jenkins
  ansible.builtin.lineinfile:
    path: /etc/default/jenkins
    regexp: '^HTTP_PORT='
    line: HTTP_PORT=9000
  become: yes

- name: Ensure Jenkins service is restarted
  service:
    name: jenkins
    state: restarted
  become: yes
