- name: Install pip
  apt:
    name: python3-pip
    state: latest
    update_cache: yes
  become: true
  # when: inventory_hostname=="checkbox"

- name: Install OpenJDK 11 using apt
  apt:
    name: openjdk-11-jdk
    state: latest
  become: true
  # when: inventory_hostname=="itrust"
